#!/bin/bash

#create kubernetes bigip login
kubectl create secret generic bigip-login -n kube-system --from-literal=username=admin --from-literal=password=admin
#create kubernetes serviceaccoutn for bigip
kubectl create serviceaccount k8s-bigip-ctlr -n kube-system
#create cluster role for bigip serviceaccount
kubectl create clusterrolebinding k8s-bigip-ctlr-clusteradmin --clusterrole=cluster-admin --serviceaccount=kube-system:k8s-bigip-ctlr

