#!/bin/bash

#delete kubernetes bigip container connection authentication and RBAC 
kubectl delete clusterrolebinding k8s-bigip-ctlr-clusteradmin
kubectl delete serviceaccount k8s-bigip-ctlr -n kube-system
kubectl delete secret bigip-login -n kube-system

#delete my-frontend
kubectl delete configmap my-frontend
kubectl delete service my-frontend
kubectl delete deployment my-frontend
