#!/bin/bash

#delete kubernetes bigip login
kubectl delete secret bigip-login -n kube-system
#delete kubernetes serviceaccoutn for bigip
kubectl delete serviceaccount k8s-bigip-ctlr -n kube-system
#delete cluster role for bigip serviceaccount
kubectl delete clusterrolebinding k8s-bigip-ctlr-clusteradmin

#delete my-frontend
kubectl delete configmap my-frontend
kubectl delete service my-frontend
kubectl delete deployment my-frontend
